apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: messaging
spec:
  replicas: 2
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_federation
      - rabbitmq_shovel
      - rabbitmq_stream
  service:
    type: LoadBalancer
