apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world
  namespace: messaging
spec:
  replicas: 2
  persistence:
    storageClassName: premium-rwo     # ajusta al tuyo
    storage: 2Gi
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_federation
      - rabbitmq_shovel
      - rabbitmq_stream
  service:
    type: LoadBalancer
