apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  default_user.conf: |
    default_user = admin
    default_pass = admin
  host: dmF1bHQtZGVmYXVsdC11c2VyLmRlZmF1bHQuc3Zj
  username: admin
  password: admin
  port: "5672"
  provider: rabbitmq
  type: rabbitmq