apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: upstream-usa
  namespace: messaging
spec:
  name: upstream-usa 

---


apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: federated-exchange-eu
  namespace: messaging
spec:
  name: orders.events
  type: topic
  vhost: "/"
  rabbitmqClusterReference:
    name: hello-world
    namespace: messaging
    

  federation:
    upstream:
      name: upstream-usa 
      uri: amqp://cluster-usa.messaging.svc.cluster.local:5672 
    upstreamRef:
      name: upstream-usa
      namespace: messaging