apiVersion: v1
kind: Secret
metadata:
  name: federation-uri
type: Opaque
data:
  uri: amqp://hello-world.messaging.svc.cluster.local:5672/archivos-remotos

---
apiVersion: rabbitmq.com/v1beta1
kind: Federation
metadata:
  name: federation-example
  namespace: messaging
spec:
  name: "origin"
  vhost: "/data-processing"
  uriSecret:
    name: federation-uri
  ackMode: "on-confirm"
  deletionPolicy: retain
  rabbitmqClusterReference:
    name: hello-world
    namespace: messaging