apiVersion: v1
kind: Secret
metadata:
  name: federation-uri
type: Opaque
data:
  uri: amqp://admin:admin@hello-world.messaging.svc.cluster.local:5672/archivos-remotos

---
apiVersion: rabbitmq.com/v1beta1
kind: Federation
metadata:
  name: federation-example
  namespace: messaging
spec:
  name: "origin"
  vhost: "/data-processing"
  uriSecret:
    # secret must be created in the same namespace as this Federation object; in this case 'rabbitmq-system'
    name: federation-uri
  ackMode: "on-confirm"
  deletionPolicy: retain
  rabbitmqClusterReference:
    name: hello-world
    namespace: messaging