apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: classic-tasks-queue
  namespace: messaging
spec:
  name: classic.queue.tasks
  vhost: "/data-processing"
  durable: true 
  arguments:
    x-queue-type: classic
  rabbitmqClusterReference:
    name: hello-world
    namespace: messaging

---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: quorum-orders-queue
  namespace: messaging
spec:
  name: quorum.queue.orders
  durable: true
  vhost: "/data-processing"
  arguments:
    x-queue-type: quorum
  rabbitmqClusterReference:
    name: hello-world
    namespace: messaging

---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: telemetry-events-stream
  namespace: messaging
spec:
  name: telemetry.events.stream
  vhost: "/data-processing"
  type: stream # without providing a queue type, rabbitmq creates a classic queue
  durable: true # mandatory for stream queues
  arguments:
    x-max-length-bytes: 1000000000 ## setting the retention policy
  deletionPolicy: retain # delete or retain; default to delete;
  rabbitmqClusterReference:
    name: hello-world
    namespace: messaging