apiVersion: v1
kind: Secret
metadata:
  name: shovel-secret
type: Opaque
data:
  destUri: # encoded value for shovel destination URI; to learn about how to construct a valid uri, see: https://www.rabbitmq.com/uri-spec.html
  srcUri: # encoded value shove source URI

---
apiVersion: rabbitmq.com/v1beta1
kind: Shovel
metadata:
  name: shovel-example
spec:
  name: "shovel-example"
  uriSecret:
    name: shovel-secret
  srcQueue: "source-queue"
  srcConsumerArgs: # optional consume arguments
    x-priority: 10
  destQueue: "destination-queue"
  destPublishProperties: # optional map of properties to overwrite when shovelling messages
    delivery_mode: 2
  deletionPolicy: retain # delete or retain; default to delete;
  rabbitmqClusterReference:
    name: hello-world