apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: data-processing-vhost
  namespace: messaging
spec:
  name: /data-processing
  rabbitmqClusterReference:
    name: hello-world
    namespace: messaging